### PR TITLE
[Foreca ui] use SetTitle if avaible

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by ims21** [comment]
Could not be used standard SetTitle as usually ? I di not know, why there is used StaticText

**Comment by Dima73** [comment]
setTitle exists in all the images?

**Comment by ims21** [comment]
I think , self["Title"] is obsolete ...  see to others plugins under E2OpenPlugins, if using it too.
But for what do you need replace self["Title"], if it works  ? Btw ... it is used 5x in code.

**Comment by Dima73** [comment]
For openPli 6.0 this self["Title"] not work.

**Comment by ims21** [comment]
Strange ... I am using it (under develop) and it works well for me ...  btw - under 6.0 foreca does not work, because there is pined old version and not 3.2.0.

**Comment by ims21** [comment]
And if is used ui.py under 6.0, title not works, because 6.0 has pinned old skin too... try develop with PLiFullHD skin and you will see, all is ok - I repaired it long time ago... enough was remove in all foreca's screens in skin_plugins.xml parameter "title=....."

f.eg:
-  <screen flags="wfNoBorder" name="ForecaPreview" position="fill" title="Forecast">
+  <screen flags="wfNoBorder" name="ForecaPreview" position="fill">

**Pull request closed without merging**
